defaultHook:
  type: merkleTreeHook
defaultIsm:
  type: 'testIsm'
  threshold: 1 # Number: Signatures required to approve a message
  validators: # Array: List of validator addresses
    - '$VALIDATOR_ADDRESS'
owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
proxyAdmin:
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
requiredHook:
  beneficiary: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  maxProtocolFee: "100000000000000000"
  owner: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
  protocolFee: "0"
  type: protocolFee

