x-common-attributes: &common
  image: gcr.io/abacus-labs-dev/hyperlane-agent:agents-v1.1.0
  environment:
    CONFIG_FILES: /config.json
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  restart: unless-stopped
  network_mode: "host"



services:
  source-validator:
    container_name: source-validator
    <<: *common

    command: ./validator --metricsPort="9090" # TODO make configurable
    volumes:
      - ./configs/config.json:/config.json
      - ./${SERVICE_NAME}/hyperlane_db:/mnt/hyperlane_db


  relayer:
    <<: *common

    command: ./relayer --metricsPort="9091" # TODO make configurable
    container_name: relayer
    volumes:
      - ./configs/config.json:/config.json
      - ./relayer/hyperlane_db:/mnt/hyperlane_db



