x-common-attributes: &common
  image: gcr.io/abacus-labs-dev/hyperlane-agent:agents-v1.1.0
  environment:
    CONFIG_FILES: /config.json
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  restart: unless-stopped
  network_mode: "host"


services:
  source-validator:
    container_name: source-validator
    <<: *common
    ports:
      - "9091:9091/tcp"
    command: ./validator
    volumes:
      - ./${SERVICE_NAME}/config.json:/config.json
      - ./${SERVICE_NAME}/hyperlane_db:/mnt/hyperlane_db


  relayer:
    <<: *common
    ports:
      - "9092:9092/tcp"
    command: ./relayer
    container_name: relayer
    volumes:
      - ./${SERVICE_NAME}/config.json:/config.json
      - ./relayer/hyperlane_db:/mnt/hyperlane_db



